# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 20:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('edit_date', models.DateTimeField(verbose_name='date edited')),
                ('content', models.TextField(default='', max_length=50000)),
            ],
            options={
                'db_table': 'Articles',
            },
        ),
        migrations.CreateModel(
            name='Contributors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('status', models.CharField(default='member', max_length=100)),
                ('active', models.SmallIntegerField(default=1)),
            ],
            options={
                'db_table': 'Contributors',
            },
        ),
        migrations.CreateModel(
            name='Contributors_articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Articles')),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Contributors')),
            ],
            options={
                'db_table': 'Contributors_articles',
            },
        ),
        migrations.CreateModel(
            name='Contributors_projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Contributors')),
            ],
            options={
                'db_table': 'Contributors_projects',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(default='', max_length=500)),
                ('contributors', models.CharField(max_length=200)),
                ('edit_date', models.DateTimeField(verbose_name='date edited')),
                ('leads', models.ManyToManyField(through='cms.Contributors_projects', to='cms.Contributors')),
            ],
            options={
                'db_table': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=500)),
                ('status', models.CharField(default='', max_length=150)),
                ('create_date', models.DateField(verbose_name='date created')),
                ('image', models.ImageField(upload_to='uploads/')),
            ],
            options={
                'db_table': 'Topics',
            },
        ),
        migrations.CreateModel(
            name='Topics_projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Projects')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Topics')),
            ],
            options={
                'db_table': 'Topics_projects',
            },
        ),
        migrations.AddField(
            model_name='topics',
            name='projects',
            field=models.ManyToManyField(through='cms.Topics_projects', to='cms.Projects'),
        ),
        migrations.AddField(
            model_name='contributors_projects',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Projects'),
        ),
        migrations.AddField(
            model_name='articles',
            name='authors',
            field=models.ManyToManyField(through='cms.Contributors_articles', to='cms.Contributors'),
        ),
        migrations.AddField(
            model_name='articles',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Projects'),
        ),
    ]
