# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('authors', models.CharField(max_length=200)),
                ('edit_date', models.DateTimeField(verbose_name='date edited')),
                ('content', models.CharField(default='', max_length=1000)),
            ],
            options={
                'db_table': 'Articles',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(default='', max_length=500)),
                ('contributors', models.CharField(max_length=200)),
                ('edit_date', models.DateTimeField(verbose_name='date edited')),
            ],
            options={
                'db_table': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=500)),
                ('status', models.CharField(default='', max_length=150)),
                ('create_date', models.DateField(verbose_name='date created')),
                ('image', models.ImageField(upload_to='uploads/')),
            ],
            options={
                'db_table': 'Topics',
            },
        ),
        migrations.CreateModel(
            name='Topics_projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Projects')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Topics')),
            ],
            options={
                'db_table': 'Topics_projects',
            },
        ),
        migrations.AddField(
            model_name='topics',
            name='projects',
            field=models.ManyToManyField(through='cms.Topics_projects', to='cms.Projects'),
        ),
        migrations.AddField(
            model_name='articles',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Projects'),
        ),
    ]
