# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='content',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
