# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_remove_projects_contributors'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributors',
            name='image',
            field=models.ImageField(default='', upload_to='uploads/team/'),
        ),
    ]
