from .settings import *

"""
Django settings for subforum_django project.

Generated by 'django-admin startproject' using Django 1.9.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'
# STATIC_ROOT = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'public/static/')
STATIC_URL = '/static/'
STATICFILES_DIRS = (os.path.join('subforum/ui/static'),)

MEDIA_ROOT = '/Users/dande_000/projects/subforum_django/subforum/ui/static/'